### ISSUE TITLE
global name 'dynamic' is not defined

### ISSUE THREAD

**Issue by capachivas** [Resonance-SDN/pyresonance#9]
Hi everyone,

When I try to launch the command pyretic.py pyretic.pyresonance.main --config=./pyretic/pyresonance/global.config --model=manual
the following error appears:

NameError: global name 'dynamic' is not defined

I guess it has to do with the fact that dynamic function does not appear neither in the pyretic nor pyresonance packages, but I cannot figure out how to solve this issue.

**Comment by brianedwin** [comment]
hi Joon, 

I just confuse how to 'git pull' from the latest branch.

Please, help me.

Thanks,

**Comment by hyojoonkim** [comment]
Hi brianedwin, 

1.First of all, this Pyresonance repository is not maintained anymore. 
We made some big changes/improvements to the code base, renamed it to “Kinetic”, and the code is now included in the Pyretic repository. It is a separate branch in the Pyretic repository. I should have pointed this out in this repository’s readme. I will do that. 

Our new project Website can be found here, with a link to the documentation/tutorial.
http://kinetic.noise.gatech.edu <http://kinetic.noise.gatech.edu/>

You can first get the Pyretic code (https://github.com/frenetic-lang/pyretic <https://github.com/frenetic-lang/pyretic>) with “git clone” command, and then switch to the “kinetic” branch.
git clone https://github.com/frenetic-lang/pyretic.git
git checkout kinetic 

Link to code of kinetic branch is here:
https://github.com/frenetic-lang/pyretic/tree/kinetic <https://github.com/frenetic-lang/pyretic/tree/kinetic>

2. That said, if you are still want this Pyresonance code base:
The latest branch means the latest code from the “master” branch. If you are already on the master branch, just type “git pull”. If you are on a different branch, first switch to the master branch (git checkout master), then type “git pull”. 

You can check which branch you are on by typing “git branch” and see where the asterisk (*) is. 

Thanks,
Joon

**Comment by EtharAlfaki** [comment]
hi Joon
i am trying to learn pyretic. i tried to run the pyretic code for simple mac learner switch .. it says that global name 'dynamic ' is not defined.
so i run the command git pull as suggested here.
but still get the error
thanks

**Comment by hyojoonkim** [comment]
Hello, 

Hmm.. That is strange. Are you using the provided VM or did you set up your own environment? 

Can you tell me in what directory you are running the command and exactly what command you are typing in? 

Also, consider using the newest Kinetic repository if that is okay with you. 
http://kinetic.noise.gatech.edu

Thanks,
Joon

**Comment by EtharAlfaki** [comment]
i am using SDN VM . 
![scrshot](https://cloud.githubusercontent.com/assets/12116498/7355200/0df276be-ed29-11e4-8803-390186d68b08.PNG)

**Comment by EtharAlfaki** [comment]
Hi 
sorry for disturbing you 
but i am trying to send JSON's event periodically on a time basis, if found a reference for similar code named time-of-day.py in your paper "Simpler Network Configuration with State-Based Network Policies" . i hope it would clarify the concept for me but i didn't find the code on pyresonance repository.
any direction will be very helpful
thanks

**Comment by hyojoonkim** [comment]
Hello,

I guess the code got missed as we migrated the source code here and there. I’m afraid I lost the code; I do not have access to machines I left behind.

That said, I think it won’t be hard to re-implement this. Will these pointers help? I think I used similar techniques.

https://docs.python.org/2/library/sched.html
or
http://stackoverflow.com/questions/15088037/python-script-to-do-something-at-the-same-time-every-day

Thanks,
Joon

On Aug 14, 2015, at 6:01 AM, EtharAlfaki <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi
sorry for disturbing you
but i am trying to send JSON's event periodically on a time basis, if found a reference for similar code named time-of-day.py in your paper "Simpler Network Configuration with State-Based Network Policies" . i hope it would clarify the concept for me but i didn't find the code on pyresonance repository.
any direction will be very helpful
thanks

**Comment by EtharAlfaki** [comment]
Thank you very much i really appreciate this

I faced another problem tying to write Round Robin server loadbalancing ,
the clients should be able to reach the public ip-address ,the controller direct the traffic of each  new host to the next server in the list and so on .. i thought this code will do it but it didn't.
if you have time i wish you can help me to understand what i did wrong 
the load balancer :
http://pastebin.com/TcjNpBeH
the monitor 
http://pastebin.com/ZV8340px

Thank you
